<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOBLTSRk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOBLTSRk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOBLTSRk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOBLTSRk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOBLTSRk\App_KernelDevDebugContainer([
    'container.build_hash' => 'OBLTSRk',
    'container.build_id' => '06ef35de',
    'container.build_time' => 1664373372,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOBLTSRk');
